on: [push, pull_request]

name: 🐂 Continuous integration

jobs:
  clippy_fmt_check_test:
    name: Rustfmt & Clippy & Check & Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Get AWS ECR credentials
        id: ecr-credentials
        run: |
          echo "::set-output name=username::AWS"
          echo "::set-output name=password::`aws ecr get-login-password`"
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ steps.ecr-credentials.outputs.username }}
          password: ${{ steps.ecr-credentials.outputs.password }}
          # private registry
          registry: 213020545630.dkr.ecr.us-west-2.amazonaws.com/oxen-server
          image_name: oxen-server
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - uses: icepuma/rust-action@master
      - run: |
          cargo build
          mkdir /tmp/oxen_sync/
          mkdir data/test/runs
          ./target/debug/oxen set-default-host 0.0.0.0:3000
          ./target/debug/oxen-server add-user --email ox@oxen.ai --name Ox --output auth_config.toml
          cp auth_config.toml data/test/config/auth_config.toml
          ./target/debug/oxen-server start &
